spring:
  datasource:
    url: jdbc:mysql://10.128.0.4:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: 1q2w3e4r
  jpa:
    properties:
      hibernate:
        format_sql: true

