spring:
  datasource:
    url: jdbc:mysql://34.136.255.139:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

