server:
  port: 9010
spring:
  application:
    name: tour-service
  datasource:
    url: jdbc:mysql://localhost:3306/destination?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled=true: